using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Core.Hazard;

/// <summary>
/// Represents a clustered danger zone formed by nearby hazard events.
/// Generated by DBSCAN algorithm in <see cref="HazardClusterAnalyzer"/>.
/// </summary>
public sealed class HazardCluster
{
    /// <summary>Unique identifier for this cluster.</summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>Center point of the cluster (average position).</summary>
    public required Vector3 Centroid { get; init; }

    /// <summary>Radius of the cluster (max distance from centroid to member).</summary>
    public required float Radius { get; init; }

    /// <summary>Events that form this cluster.</summary>
    public required IReadOnlyList<HazardEvent> Events { get; init; }

    /// <summary>Total number of events in this cluster.</summary>
    public int EventCount => Events.Count;

    /// <summary>Timestamp of most recent event in cluster.</summary>
    public DateTime LastIncident => Events.Count == 0 ? DateTime.MinValue : Events.Max(e => e.Timestamp);

    /// <summary>Timestamp of first event in cluster.</summary>
    public DateTime FirstIncident => Events.Count == 0 ? DateTime.MinValue : Events.Min(e => e.Timestamp);

    /// <summary>Severity score (calculated by <see cref="HazardAnalytics"/>).</summary>
    public float SeverityScore { get; set; }

    /// <summary>Map ID for spatial queries.</summary>
    public int MapId => Events.Count > 0 ? Events[0].MapId : 0;

    /// <summary>
    /// Tests if a position falls within this hazard zone.
    /// </summary>
    public bool ContainsPosition(Vector3 position, float safetyMargin = 0f)
    {
        float distance = Vector3.Distance(position, Centroid);
        return distance <= (Radius + safetyMargin);
    }
}

